
# Introduction to Numpy
    
<img src='images/Numpy.jpg' alt = "Numpy" style="width:600; height:300"/>    


## Objectives

In this section of the course, students will learn how to import Numpy library, create both one and two dimensional array and do various operations with it. At the end of the Numpy section, students will be able to work and maniputate n dimensional array and be able to work with linear algebra and solve some simple system of linear equations.

## Table of content

* Introduction to Numpy
* Installation instruction guide
* How to import Numpy library
* Python Lists and NumPy Arrays
* Array Slicing
* Numpy Attributes
* Other ways to create arrays
* Multi dimensional array
* Systems of Linear Equations

# Introduction to Numpy
NumPy is a Python package/librarry that stands for `Numerical Python`. It is the core library for scientific computing, which contains a powerful n-dimensional array object. It is also a linear algebra for python and almost all of the libraries in the Python ecosystem rely on it as one of their main building blocks. It is incredibly fast, as it has bindings to C libraries.

## **Prerequisites**

A basic understanding of Python programming in CS14 (Programming in Python) is required. 

## Importing the NumPy module

In [1]:
import numpy as np

## Python Lists and NumPy Arrays

This section introduces NumPy arrays then explains the difference between Python lists and NumPy arrays. NumPy is used to construct homogeneous arrays and perform mathematical operations on arrays. A NumPy array is different from a Python list. The data types stored in a Python list can all be different.


In [2]:
python_list = ["Ethiopia", 5, 17.9, True]

type(python_list)

list

The Python list above contains four different data types:
- "Ethiopia" is a string
- 5 is an integer
- 17.9 is a float, 
- True is a boolean.

## What is Python Numpy Array?
NumPy arrays are a bit like Python lists, but still very much different at the same time. The simplest way to create an array in Numpy is to use Python List.

In [5]:
myPythonList = [1, 4, 7, 2, 12, 17]

We can convert python list to a numpy array by using the object np.array.

In [6]:
numpy_array_from_list = np.array(myPythonList)

type(numpy_array_from_list)

numpy.ndarray

**To display the output**:

In [7]:
numpy_array_from_list

array([ 1,  4,  7,  2, 12, 17])

In practice, there is no need to declare a Python List. The operation can be combined.

In [8]:
new_array  = np.array([1, 9, 8, 3, 12])
new_array

array([ 1,  9,  8,  3, 12])

In [9]:
l1 = [1, 2, 3, 5, 7]

In [10]:
l1+1

TypeError: can only concatenate list (not "int") to list

In [11]:
k2 = np.array([1, 2, 3, 5, 7])

In [12]:
k2+1

array([2, 3, 4, 6, 8])

## Mathematical operations on one dimensional array
You can perform mathematical operations like additions, subtraction, division, and multiplication on an array. The syntax is the array name followed by the operation (+, -, *, /).

## Example 1

In [13]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Addition
a + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
# Subtraction
a - 3

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [15]:
# Multiplication
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
# Division
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [17]:
# Exponentiation

a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

## Example 2

When standard mathematical operations are used with arrays, they are applied on an element-by-element basis. This means that the arrays should be the same size during addition,
subtraction, etc.

In [2]:
a = np.array([5, 2, 7, 4, 12])

b = np.array([3, 2, 4, 1, 6])

In [19]:
print(a + b)

[ 8  4 11  5 18]


In [20]:
print(a - b)

[2 0 3 3 6]


In [21]:
print(a * b)

[15  4 28  4 72]


In [22]:
print(b / a)


[0.6        1.         0.57142857 0.25       0.5       ]


In [23]:
print(a % b) # Remainder when you divide each of the elements in a by b

[2 0 3 0 0]


In [24]:
b**a

array([        243,           4,       16384,           1, -2118184960],
      dtype=int32)

In [5]:
a

array([ 5,  2,  7,  4, 12])

In [6]:
np.sqrt(a) # square root of each of the elements in a

array([2.23606798, 1.41421356, 2.64575131, 2.        , 3.46410162])

# One-dimensional Array Indexing

Array elements are accessed, sliced, and manipulated just like lists. 

In [7]:
a = np.array([1, 2, -1, 4, -5, 6, 7, 0, 9, 10])

print(a)

[ 1  2 -1  4 -5  6  7  0  9 10]


**Remember counting in Python starts at 0 and ends at n-1**.

The index (or location) of each value in the array is shown below:

The value 1 has an index of 0. We could also say 1 is in location 0 of the array. The value 4 has an index of 3 and the value 8 has an index of 9. 

In [8]:
a[0] # accessing the first element in array a

1

In [9]:
a[3] # accessing the third element in array a

4

In [10]:
a[8]

9

In [11]:
a[2] = 5 # accessing the first element in array a and replacing the result with 5
a

array([ 1,  2,  5,  4, -5,  6,  7,  0,  9, 10])

# Array Slicing

Values stored within an array can be accessed simultaneously with array slicing. To pull out a section or slice of an array, the colon operator : is used when calling the index. The general form is:

`array [start : stop]`

The index of the slice is specified in `[start : stop]`. Remember Python counting starts at $0$ and ends at $n-1$. The index `[0 : 2]` pulls the first two values out of an array. The index `[1 : 3]` pulls the second and third values out of an array.

# Example 1

In [14]:
a = np.array([2, 4, 6, 5, 8, 9])

print(a)

[2 4 6 5 8 9]


In [15]:
type(a)

numpy.ndarray

In [16]:
b = a[0:2] # 0, 1

print(b)

[2 4]


## Example 2

In [17]:
x = np.array([5, 8, 9, 2, 4, 6, 5])

print(x)

[5 8 9 2 4 6 5]


In [18]:
print(x[1:3]) # 1, 2

[8 9]


On either sides of the colon, a blank stands for "default".

- `[:2]` corresponds to `[start=default:stop=2]`
- `[1:]` corresponds to `[start=1:stop=default]`

Therefore, the slicing operation `[:2]` pulls out the first and second values in an array. The slicing operation `[1:]` pull out the second through the last values in an array. The examples below illustrate the default stop value is the last value in the array.

## Example 4

In [19]:
a = np.array([2, 4, 6, 8, 10, 0, 1, 5])
print(a)

[ 2  4  6  8 10  0  1  5]


In [30]:
b = a[1:]
print(b)

[ 4  6  8 10  0  1  5]


## Example 5

In [20]:
x = np.array([0, 5, 6, 1, 0, 8, 1, 5, 9])
print(x)

[0 5 6 1 0 8 1 5 9]


In [21]:
y = x[2:]
print(y)

[6 1 0 8 1 5 9]


The next examples shows the default `start` value is the first value in the array.

In [33]:
a = np.array([2, 4, 6, 8, 1, 3, 6])
print(a)

[2 4 6 8 1 3 6]


In [34]:
b = a[:3]
print(b)

[2 4 6]


The following indexing operations output the same array.

In [22]:
a = np.array([2, 1, 7, 4, 6, 8, 3])

b = a[0:7] # [start=0:stop= 6]

print(b)

c = a[:7] # [start=0:stop= 6]

print(c)

d = a[0:] # [start=0:stop= 6]

print(d)

e = a[:] # [start=0:stop= 6]

print(e)

[2 1 7 4 6 8 3]
[2 1 7 4 6 8 3]
[2 1 7 4 6 8 3]
[2 1 7 4 6 8 3]


# Numpy Attributes

Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get the intrinsic properties of the array. Some commonly used attributes are:

* shape:    indicates the dimension of an array
* size:     returns the total number of elements in the array
* dtype:    returns the type of elements in the array, i.e., int64, character


You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes.


## Example 1

In [23]:
even_array  = np.array([2, 4, 6, 8, 10, 12, 14, 16])

even_array

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
# dimension of the array

print(even_array.shape)

(8,)


In [26]:
even_array.shape

(8,)

In [25]:
# total element in the array
print(even_array.size)

8


In [27]:
even_array.size

8

In [28]:
# datatype in the array
print(even_array.dtype) 

int32


In [29]:
even_array.dtype

dtype('int32')

## Example 2

In [30]:
some_array = np.array([12, 62, 65,  7, 21, 60, 10, 87, 14, 43, 51, 10, 38, 95, 26, 11, 46, 47, 34, 68, 58, 77, 13, 10, 45])

some_array

array([12, 62, 65,  7, 21, 60, 10, 87, 14, 43, 51, 10, 38, 95, 26, 11, 46,
       47, 34, 68, 58, 77, 13, 10, 45])

In [31]:
some_array.shape

(25,)

In [32]:
some_array.size

25

# Other ways to create arrays

### arange
The arange function is similar to the range function but returns an array:

In [33]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [35]:
np.arange(5, 100, 25)

array([ 5, 30, 55, 80])

### linspace
Return evenly spaced numbers over a specified interval.

In [36]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [37]:
np.linspace(0, 50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [38]:
len(np.linspace(0, 50, 10))

10

# Multi dimensional array

Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation. A simple 2-D array is defined by a list of lists. Here is an example with a two-dimensional array (e.g. a matrix).

## Example 1

$A = 
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}$


In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
type(A)

numpy.ndarray

In [5]:
A.shape # dimension of the array. This returns a tupple

(3, 3)

In [6]:
print(A.size)# Total elements in the array

9


In [7]:
A.dtype

dtype('int32')

## Example 2

$another\_array = 
\begin{pmatrix}
5 & 6 & 7 \\
4 & 2 & 1 \\
3 & 7 & 1
\end{pmatrix}$

In [8]:
another_array = np.array([[5, 6, 7], [4, 2, 1], [3, 7, 1]])

print(another_array)

[[5 6 7]
 [4 2 1]
 [3 7 1]]


In [9]:
print(another_array.shape) 

(3, 3)


In [10]:
print(another_array.size)

9


In [11]:
B = np.array([[4, 6, 8], [2, 3, 1]])

In [12]:
B

array([[4, 6, 8],
       [2, 3, 1]])

In [13]:
B.shape

(2, 3)

## Two-Dimensional Array Indexing

Values in a 2-D array can be accessed using the general notation below:

`value = array name [row, col]`

Where **value** is the value pulled out of the 2-D array and `[row, col]` specifies the row and column index of the value. Remember Python counting starts at 0, so the first row is row zero and the first column is column zero. We can access the value 2 in the array above by calling the row and column index `[0, 1]`. This corresponds to the 1st row (remember row 0 is the first row) and the 2nd column (column 0 is the first column).


$A = 
\begin{matrix}
C0& C1 & C2\\
1 & 2 & 3 & R0 \\
4 & 5 & 6 & R1 \\
7 & 8 & 9& R 2
\end{matrix}$


## Example 1

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
A[ 0, 1] # value 2 is is row 0 and column 1

2

In [16]:
A[ 1, 2 ]

6

In [17]:
A[1, 0] # value 4 is is row 1 and column 0

4

## Example 2

In [19]:
a = np.array([[2,3,4],[6,7,8]])

print(a)

[[2 3 4]
 [6 7 8]]


In [20]:
a[1, 2]

8

In [21]:
a[1, 2] = 20

In [67]:
print(a)

[[ 2  3  4]
 [ 6  7 20]]


In [23]:
a[0 , 1 ] = 9

In [24]:
a

array([[ 2,  9,  4],
       [ 6,  7, 20]])

## Other array indexing

2D NumPy arrays can also be sliced with the general form:

`array[row = start_row:end_row, col = start_col:end_col]`

The code section below creates a two row by four column array and indexes out the first two rows and the first three columns.

In [25]:
a = np.array([[2, 4, 6, 8], [0, 5, 4, 1]])
print(a)

[[2 4 6 8]
 [0 5 4 1]]


In [26]:
a.shape

(2, 4)

In [27]:
b = a[0:2, 0:3]

print(b)

[[2 4 6]
 [0 5 4]]


The code section below slices out the first two rows and all columns from array a.

In [28]:
b = a[:2, :]  #[first two rows, all columns]

print(b)

[[2 4 6 8]
 [0 5 4 1]]


Again, a blank represents defaults the first index or the last index. The colon operator all by itself also represents "all" (default start: default stop).

In [29]:
b = a[:, :]  #[all rows, all columns]
print(b)

[[2 4 6 8]
 [0 5 4 1]]
