<img src='images/Numpy.jpg' alt = "Numpy" style="width:600; height:300"/>    


## Mathematical operations on one dimensional NumPy arrays

Once you have a NumPy array, you can perform mathematical operations on the entire array without writing explicit loops. This ability is called *vectorization*. It is one of the main reasons NumPy is so powerful and it is the same idea that pandas uses when you perform operations on a column of a DataFrame.

In a one dimensional array, operations are applied elementwise. If `a` is an array, expressions like `a + 2`, `a * 10`, or `a / 3` operate on every value inside `a`.

### Example 1: Scalar operations on an array

In [2]:
import numpy as np

# A simple one dimensional array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Addition: add 2 to every element
a + 2

In [ ]:
# Subtraction: subtract 3 from every element
a - 3

In [ ]:
# Multiplication: multiply every element by 2
a * 2

In [ ]:
# Division: divide every element by 4
a / 4

These operations are similar to what you will later do with pandas Series, where each column behaves like a NumPy array under the hood.

---

## Example 2: Elementwise operations between two arrays

You can also perform operations between two arrays. NumPy will apply the operation element by element, as long as the arrays are compatible in size or can be broadcast.

In [ ]:
# Two arrays of the same length
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

# Elementwise addition
a + b

In [ ]:
# Elementwise subtraction
a - b

In [ ]:
# Elementwise multiplication
a * b

In [ ]:
# Elementwise division
a / b

In [ ]:
# Elementwise power
b ** a

In [ ]:
# Elementwise remainder (modulo)
a % b

If arrays have compatible shapes, NumPy uses *broadcasting* to match their shapes and still perform elementwise operations. This idea will later help you when you combine pandas columns with constants or with other columns.

---

## Example 3: Quick statistics with NumPy (preparing for pandas)

In data science, you often need quick summary statistics. NumPy provides fast methods for this. Imagine you are working with students’ test scores.

In [ ]:
# Scores out of 100 for a group of students
scores = np.array([55, 68, 72, 80, 90, 64, 77, 85, 92, 70])

scores.mean()       # average score

In [ ]:
scores.min(), scores.max()   # minimum and maximum

In [ ]:
scores.std()        # standard deviation

In [ ]:
scores.sum()        # total of all scores

Exactly the same style of operations will later apply to pandas columns:

* `scores.mean()` looks like `df["score"].mean()` in pandas.
* `scores.std()` looks like `df["score"].std()` in pandas.

So learning these functions in NumPy makes the move into pandas very natural.

---

## Example 4: Boolean indexing and filtering

Boolean indexing allows you to filter values based on a condition. This is a very common data science pattern and is also used heavily in pandas.

In [ ]:
scores = np.array([55, 68, 72, 80, 90, 64, 77, 85, 92, 70])

# Check which scores are at least 70
scores >= 70

In [ ]:
# Filter scores that are at least 70
scores[scores >= 70]

In [ ]:
# Filter scores that are below 60
scores[scores < 60]

You can combine conditions using logical operators.

In [ ]:
# Scores between 70 and 85 inclusive
scores[(scores >= 70) & (scores <= 85)]

Later in pandas, this will become very similar:

In [ ]:
# In pandas (preview, do not run now)
# df[df["score"] >= 70]

---

## Example 5: Reshaping arrays for tabular data

Most real datasets are naturally two dimensional (rows and columns), which is how pandas DataFrames work. NumPy provides the `.reshape()` method to change the shape of an array without changing the underlying data.

In [ ]:
# A one dimensional array with 12 elements
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
data.shape

In [ ]:
# Reshape to a 3x4 matrix (3 rows, 4 columns)
data_3x4 = data.reshape(3, 4)
data_3x4

In [ ]:
data_3x4.shape

This is very similar to having a small table with 3 rows and 4 columns, which is how pandas will store your data internally.

Another useful trick is using `-1` to let NumPy infer one of the dimensions.

In [ ]:
# Reshape to 4 rows, let NumPy figure out the number of columns
data_4_rows = data.reshape(4, -1)
data_4_rows

---

## Universal array functions (ufuncs)

NumPy provides many fast, vectorized functions that operate elementwise on arrays. These are called *universal functions* or *ufuncs*. They are widely used in data science to transform and clean data before loading it into pandas or while working with pandas.

In [ ]:
a = np.array([1, 4, 9, 16, 25, 36])

np.sqrt(a)   # square root of each element

In [ ]:
np.exp(a)    # e^x for each element

In [ ]:
np.log(a)    # natural logarithm of each element

In [ ]:
np.sin(a)    # sine of each element (in radians)

You can also combine ufuncs with boolean indexing to perform conditional transformations.

### Example 6: Simple data transformation workflow

Imagine you have daily sales amounts in Naira and you want to:

* Convert them to thousands of Naira
* Clip very large values for analysis
* Apply a log transformation to reduce skewness

In [3]:
sales = np.array([12000, 55000, 23000, 98000, 150000, 40000, 75000])

# Convert to thousands of Naira
sales_k = sales / 1000
sales_k

array([ 12.,  55.,  23.,  98., 150.,  40.,  75.])

In [4]:
# Clip values above 100k to 100k (cap extreme values)
sales_clipped = np.clip(sales, a_min=0, a_max=100000)
sales_clipped

array([ 12000,  55000,  23000,  98000, 100000,  40000,  75000])

In [5]:
# Add 1 and apply log transform (to avoid log(0))
sales_log = np.log(sales_clipped + 1)
sales_log

array([ 9.39274526, 10.91510665, 10.04329297, 11.49273296, 11.51293546,
       10.59665973, 11.22525673])