<img src='images/Numpy.jpg' alt = "Numpy" style="width:600; height:300"/>    

# Indexing and Slicing NumPy Arrays

Once you have created arrays, the next important skill is learning how to *access* and *work with* specific elements, rows, columns, or blocks inside those arrays. This process is called **indexing** and **slicing**.

NumPy indexing is very similar to what you already know from Python lists, but with powerful extensions that are extremely useful in data science. The same ideas will later appear again when we work with pandas `Series` and `DataFrame` objects.

NumPy uses **zero-based indexing**, so the first element is at index `0`, the second at `1`, and so on.

---

## Indexing and Slicing One-Dimensional Arrays

Let us start with a simple one-dimensional array of ages:

| Positive Index | 0 | 1 | 2 | 3 | 4 | 5 |
|----------------|---|---|---|---|---|---|
| Ages           | 18| 20| 22| 19| 21| 23|
|**Negative Index** | **-6**| **-5**| **-4**| **-3**| **-2**|**-1**|

In [1]:
import numpy as np

ages = np.array([18, 20, 22, 19, 21, 23])
ages

array([18, 20, 22, 19, 21, 23])

#### Accessing single elements

In [2]:
ages[0]      # first element (18)

18

In [3]:
ages[-1]     # last element (23)

23

In [4]:
ages[2]      # third element (22)

22

#### Basic slicing with start, stop, and step

In [5]:
ages[1:4]    # elements at index 1, 2, 3 -> [20, 22, 19]

array([20, 22, 19])

In [6]:
ages[:3]     # first three elements -> [18, 20, 22]

array([18, 20, 22])

In [7]:
ages[3:]     # from index 3 to the end -> [19, 21, 23]

array([19, 21, 23])

In [8]:
ages[::2]    # every second element -> [18, 22, 21]

array([18, 22, 21])

In [9]:
ages[::-1]   # reverse the array -> [23, 21, 19, 22, 20, 18]

array([23, 21, 19, 22, 20, 18])

#### Modifying elements through indexing

Indexing also allows you to change values in place. This is a common operation in data cleaning and preprocessing.

In [10]:
ages[0] = 19          # correct a data entry

In [11]:
ages[2:4] = [21, 20]  # update a slice of the array

In [12]:
ages

array([19, 20, 21, 20, 21, 23])

#### Boolean indexing (filtering values)

Boolean indexing is particularly important in data science. You create a logical condition and use it to filter the array.

In [13]:
ages = np.array([18, 20, 22, 19, 21, 23])

# create a boolean mask
mask = ages >= 21
mask

array([False, False,  True, False,  True,  True])

In [14]:
# use the mask to filter the array
adult_ages = ages[mask]
adult_ages

array([22, 21, 23])

In [15]:
# you can also write it in one line
ages[ages < 20]   # all ages less than 20

array([18, 19])

This style of filtering is exactly the kind of operation we will later perform on pandas `Series` and `DataFrame` columns when we subset rows based on conditions.

---

## Indexing and Slicing Two-Dimensional Arrays

Two-dimensional arrays represent tables or matrices. Think of them as data with rows and columns, similar to a spreadsheet or a pandas `DataFrame`.

In [16]:
scores = np.array([[65, 70, 80],
                   [75, 85, 90],
                   [55, 60, 65]])
scores

array([[65, 70, 80],
       [75, 85, 90],
       [55, 60, 65]])

Conceptually,

<table>
<tr>
<td width="50%">

**Rows:**
* Row 0: `[65, 70, 80]` 
* Row 1: `[75, 85, 90]`
* Row 2: `[55, 60, 65]`

</td>
<td width="50%">

**Columns:**
* Column 0: `[65, 75, 55]` 
* Column 1: `[70, 85, 60]`
* Column 2: `[80, 90, 65]`

</td>
</tr>
</table>

#### Accessing single elements

To access a single value, you provide `[row_index, column_index]`.

In [50]:
scores[0, 0]   # first row, first column -> 65

65

In [51]:
scores[1, 2]   # second row, third column -> 90

90

In [52]:
scores[2, 1]   # third row, second column -> 60

60

#### Accessing entire rows or columns

In [20]:
scores[0]        # entire first row -> [65, 70, 80]

array([65, 70, 80])

In [21]:
scores[1]        # second row -> [75, 85, 90]

array([75, 85, 90])

In [22]:
scores[:, 0]     # entire first column -> [65, 75, 55]

array([65, 75, 55])

In [23]:
scores[:, 2]     # entire third column -> [80, 90, 65]

array([80, 90, 65])

#### Slicing sub-matrices

You can slice out rectangular blocks of the table.

In [24]:
scores[:, 1:3]   # all rows, columns 1 and 2

array([[70, 80],
       [85, 90],
       [60, 65]])

In [25]:
scores[0:2, :]   # first two rows, all columns

array([[65, 70, 80],
       [75, 85, 90]])

In [26]:
scores[1:, 1:]   # from row 1 and column 1 to the end

array([[85, 90],
       [60, 65]])

#### Modifying values in a matrix

In [27]:
# increase all scores in the first row by 5
scores[0, :] = scores[0, :] + 5

In [28]:
# set the entire third column to 100
scores[:, 2] = 100

scores

array([[ 70,  75, 100],
       [ 75,  85, 100],
       [ 55,  60, 100]])

Operations like “update all scores in a column” or “adjust scores for some rows” are very common in data science workflows.

---

###  More Examples: Practical Data Science Operations

Below are a few more examples that mirror real data science tasks.

#### Example 1: Normalizing exam scores

Suppose the scores for the second test are stored in the second column. We may want to scale them to a 0–1 range for modeling.

In [29]:
scores = np.array([[65, 70, 80],
                   [75, 85, 90],
                   [55, 60, 65]])

second_test = scores[:, 1]          # extract the second column
min_val = second_test.min()
max_val = second_test.max()

scaled_second_test = (second_test - min_val) / (max_val - min_val)
scaled_second_test

array([0.4, 1. , 0. ])

#### Example 2: Selecting students who scored above a threshold

In [30]:
total_scores = scores.sum(axis=1)   # sum across columns for each row
total_scores

array([215, 250, 180])

In [31]:
# create a mask for students with total score at least 200
high_performers_mask = total_scores >= 200
high_performers_mask

array([ True,  True, False])

In [32]:
# select only rows for high performing students
high_performers = scores[high_performers_mask, :]
high_performers

array([[65, 70, 80],
       [75, 85, 90]])

This is directly comparable to selecting rows in a pandas `DataFrame` where a total score column exceeds a threshold.

#### Example 3: Selecting every other row and column

In [56]:
# every other row, every other column
subsample = scores[::2, ::2]
subsample

array([[65, 80],
       [55, 65]])

Subsampling like this is useful for quick checks, exploratory analysis, or when you are working with very large datasets.

---

### 6.4 How This Connects to pandas

The ideas you see here are the foundation for how we work with data in pandas:

* Selecting columns in a `DataFrame` feels similar to slicing columns in a NumPy array.
* Selecting specific rows and columns using `.iloc` in pandas mirrors the `[row_index, column_index]` style in NumPy.
* Filtering rows using conditions in pandas uses the same idea as boolean indexing in NumPy.

For example, the following operations:

In [ ]:
scores[0, 1]      # element at row 0, column 1

70

In [35]:
scores[:, 0]      # all rows, first column

array([65, 75, 55])

In [36]:
scores[total_scores >= 200, :]   # rows where total score is at least 200

array([[65, 70, 80],
       [75, 85, 90]])

closely mirror the way we will later write:

In [ ]:
df.iloc[0, 1]           # first row, second column in pandas
df.iloc[:, 0]           # entire first column
df[df["total"] >= 200]  # rows where total score is at least 200

df.iloc[0, 1]           # first row, second column in pandas
df.iloc[:, 0]           # entire first column
df[df["total"] >= 200]  # rows where total score is at least 200

Understanding indexing and slicing in NumPy therefore prepares you very well for working with real-world datasets using pandas in data science projects.